### ISSUE TITLE
windows下可以运行么？

### ISSUE THREAD

**Issue by alannewlife** [smiecj/docker-centos#27]
![image](https://user-images.githubusercontent.com/21301160/234194189-7261d4e0-f850-48fb-863b-5bf537a483aa.png)

请问这套部署架构windows下可以运行么？

※wls2和dockdesktop都有，正常运行。

**Comment by alannewlife** [comment]
然后，我单独下载安装了一个。
想启动ssh，总是不行。

> 
docker run -itd --privileged=true --name dev1 mzsmieli/centos_python /usr/sbin/init 

>
systemctl start sshd.service

**Comment by alannewlife** [comment]
>执行  systemctl start sshd.service 的错误如下：

Redirecting to /bin/systemctl start sshd.service
System has not been booted with systemd as init system (PID 1). Can't operate.

sysemctl怎么都运行不了，但试了一个空的centos8，运行sysemctl是可以的。

**Comment by alannewlife** [comment]
>执行  systemctl start sshd.service 的错误如下：

Redirecting to /bin/systemctl start sshd.service
System has not been booted with systemd as init system (PID 1). Can't operate.

sysemctl怎么都运行不了，但试了一个空的centos8，运行sysemctl是可以的。

**Comment by smiecj** [comment]
抱歉，这两天才有时间看这个问题

systemctl 存在对 M1 Mac兼容性问题，所以默认我是没装 systemctl 的。常驻服务我都通过 s6 去启动（ 比如 mysql，参考 Dockerfiles/backend/mysql/s6/services.d/mysql ）

然后我刚刚提交了一个版本，支持通过 docker run -e INIT_SERVICE="ssh" 启动 ssh，放在 [dev_init](https://github.com/smiecj/docker-centos/tree/dev_init) 分支 你可以试一下。需要先构建 base 镜像再构建 python （dockerhub 上的镜像还没更新）

你可以大概看一下[实现](https://github.com/smiecj/docker-centos/compare/main...dev_init#diff-6ac6207ac27acc8f24affd0bf266a5bf6737f70e5c17943c93676d954253f593R3)，没问题的话我把 hub 上的镜像更新下
